// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: messages.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetScoreService_GetScore_FullMethodName = "/pb.GetScoreService/GetScore"
)

// GetScoreServiceClient is the client API for GetScoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetScoreServiceClient interface {
	GetScore(ctx context.Context, in *VectorRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type getScoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetScoreServiceClient(cc grpc.ClientConnInterface) GetScoreServiceClient {
	return &getScoreServiceClient{cc}
}

func (c *getScoreServiceClient) GetScore(ctx context.Context, in *VectorRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, GetScoreService_GetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetScoreServiceServer is the server API for GetScoreService service.
// All implementations must embed UnimplementedGetScoreServiceServer
// for forward compatibility.
type GetScoreServiceServer interface {
	GetScore(context.Context, *VectorRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedGetScoreServiceServer()
}

// UnimplementedGetScoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetScoreServiceServer struct{}

func (UnimplementedGetScoreServiceServer) GetScore(context.Context, *VectorRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedGetScoreServiceServer) mustEmbedUnimplementedGetScoreServiceServer() {}
func (UnimplementedGetScoreServiceServer) testEmbeddedByValue()                         {}

// UnsafeGetScoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetScoreServiceServer will
// result in compilation errors.
type UnsafeGetScoreServiceServer interface {
	mustEmbedUnimplementedGetScoreServiceServer()
}

func RegisterGetScoreServiceServer(s grpc.ServiceRegistrar, srv GetScoreServiceServer) {
	// If the following call panics, it indicates UnimplementedGetScoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetScoreService_ServiceDesc, srv)
}

func _GetScoreService_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetScoreServiceServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetScoreService_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetScoreServiceServer).GetScore(ctx, req.(*VectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetScoreService_ServiceDesc is the grpc.ServiceDesc for GetScoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetScoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GetScoreService",
	HandlerType: (*GetScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _GetScoreService_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
