services:
  api1:
    build:
      context: ..
      dockerfile: containerization/Dockerfile
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"

          memory: "171MB"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/ready"]
      interval: 10s
      timeout: 3s
      retries: 3

  api2:
    build:
      context: ..
      dockerfile: containerization/Dockerfile
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "171MB"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/ready"]
      interval: 10s
      timeout: 3s
      retries: 3

  lb:
    image: nginx:alpine
    networks:
      - rinha
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "8MB"

networks:
  rinha:
    driver: bridge
  
